name: memos_one
description: Offline-first native client for Memos. One Client. Every Device. Your Memos.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  drift: ^2.22.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.5
  flutter_markdown: ^0.7.4+3
  uuid: ^4.5.1
  collection: ^1.19.0
  equatable: ^2.0.7
  intl: ^0.20.2
  connectivity_plus: ^6.1.1
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  window_manager: ^0.4.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
